[package]
name = "sqler"
version = "0.1.0"
edition = "2021"

[features]
default = ["tsql"]
tsql = []

[dependencies]
logos = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
