[package]
name = "sqler"
version.workspace = true
edition.workspace = true

[lib]
name = "sqler"
path = "src/lib.rs"

[features]
default = ["tsql"]
tsql = []

[dependencies]
logos = { workspace = true }
thiserror = { workspace = true }
