name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get all history for debugging
    
    - name: Debug git status
      run: |
        echo "Git status:"
        git status
        echo -e "\nTracked files:"
        git ls-files
        echo -e "\nVerify Cargo.toml files:"
        git ls-files | grep Cargo.toml
        echo -e "\nDirectory contents:"
        ls -R

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose