name: Rust CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get current version
      id: current_version
      run: |
        VERSION=$(grep -m1 'version = "' Cargo.toml | cut -d '"' -f2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Check if version tag exists
      id: check_tag
      run: |
        if git ls-remote --tags origin "refs/tags/v${{ steps.current_version.outputs.version }}" | grep -q .; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Configure Git
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Create and Push Tag
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        VERSION=${{ steps.current_version.outputs.version }}
        git tag "v$VERSION"
        git push origin "v$VERSION"

    - name: Create Release
      if: steps.check_tag.outputs.exists == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${{ steps.current_version.outputs.version }}
        gh release create "v$VERSION" \
          --title "Release v$VERSION" \
          --generate-notes

    - name: Publish to crates.io
      if: steps.check_tag.outputs.exists == 'false'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        # Get the version
        VERSION=${{ steps.current_version.outputs.version }}
        
        # Publish sqler library first
        cargo publish -p sqler
        
        # Wait for crates.io to process the library
        sleep 30
        
        # Update sqler-cli's dependency to use the published version
        sed -i 's|sqler = { path = "../sqler" }|sqler = "'$VERSION'"|' sqler-cli/Cargo.toml
        
        # Then publish the CLI tool
        cargo publish -p sqler-cli
        
        # Revert the change to Cargo.toml to keep the local development setup
        git checkout sqler-cli/Cargo.toml
